baseURL = "https://migvidal.netlify.app/"
title = "Migvidal"

languageCode = "es"
DefaultContentLanguage = "es"

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    contentDir = 'content/en'
    weight = 1
  [languages.es]
    disabled = false
    languageCode = 'es'
    contentDir = 'content/es'
    weight = 2

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "Nusser Studios"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/migvidal/"
linkedin = "https://www.linkedin.com/in/migvidal/"
dribbble = "https://dribbble.com/miguelvidal/"
behance = "https://www.behance.net/migvidal"
og_image = "/images/tailbliss-cover.png"
sitename = "Migvidal"
twitter = "https://twitter.com/migvidal_dev/"
description = "Miguel Vidal"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"
